### ISSUE TITLE
unable to run deploy command

### ISSUE THREAD

**Issue by gshap** [YaleDHLab/gathering-a-building#111]
[latest attempt: missing script: chmod]

Gideons-MacBook-Pro:gathering-a-building GFS$ npm run chmod 600 gathering-a-building-server.pem
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "chmod" "600" "gathering-a-building-server.pem"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9

npm ERR! missing script: chmod
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/GFS/gathering-a-building/npm-debug.log
Gideons-MacBook-Pro:gathering-a-building GFS$ chmod 600 gathering-a-building-server.pem

**Comment by duhaime** [comment]
Ah, it looks like that error sprang because you ran `npm run chmod 600 gathering-a-building-server.pem`. The first step is to run `chmod 600 gathering-a-building-server.pem` then run `npm run deploy`...

I just updated the README to reflect the chmod step (you only need to run it once, and I've just grown accustomed to running it as a matter of course and then forgetting about it).

**Comment by duhaime** [comment]
@gshap Are you still having trouble deploying, or can we close this one out?
