### ISSUE TITLE
Design QA 1.1: Landing Page

### ISSUE THREAD

**Issue by ghost** [YaleDHLab/gathering-a-building#72]
- [x] New landing page image now available
- [x] Let image bleed to bottom of screen (no need for bottom margin on home page)
- [x] Rollover color: #F5711E
- [x] Background color gradient: #C8D8F1
- [x] Overlay title heading (i.e. "Material Journeys »") typeface: Mallory book
- [x] Menu subtitles: Mallory Light
- [x] Menu: Include "Login" link?

**Comment by duhaime** [comment]
Is Mallory a good font face for the overlay title heading and the Menu subtitles? We're loading that font from a ttf file, so it'd be nice to leverage that font for those elements if we can! Otherwise I can plug in the other font files, I just thought we'd want to use the one we're loading where we can.

Once the video sequence is finalized, we can photoshop the last image of the video sequence and use that for the new landing page background image. I think we'll want to finalize the video sequence first though, as it will determine the cropping and aspect ratio required of that final image...

**Comment by duhaime** [comment]
closed via style-roundup branch
